### ISSUE TITLE
Bug: Cron jobs end up creating PRs under the same branch names 

### ISSUE THREAD

**Issue by rdimitrov** [vmware/repository-service-tuf#109]
### What happened?

The automation we added using cron jobs which update daily our python dependencies and sync the submodule end up creating PRs using the same branch name and thus overwriting their changes. 

@kairoaraujo - I suggest we avoid merging anything from the automated PRs until we resolve this 👍 

### Relevant log output

```shell
https://github.com/vmware/repository-service-tuf/pull/108
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
I tagged the PR bellow with DON'T MERGE
- #108
