### ISSUE TITLE
bug: FT needs to be a job

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf#136]
The error:
https://github.com/vmware/repository-service-tuf/actions/runs/3435030501

Possible solution:
The FT needs to be a job instead a step (?)

https://github.com/vmware/repository-service-tuf/blob/48eac5cdf937baa9cfe1de5a12913826daaba3f7/.github/workflows/update-submodules.yml#L17-L22

**Comment by kairoaraujo** [comment]
@rdimitrov

**Comment by rdimitrov** [comment]
I'll be on it 👍
