### ISSUE TITLE
Feature: simplify the metadata bootstrap process

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf#208]
### What is the feature about?

The current bootstrap process creates the entire TUF Metadata from the CLI (Root, Targets, Timestamp, Snapshot, and Delegated Roles bins).

The idea is to simplify this process by changing some flows.

- Create only the Metadata required on the CLI using the [Offline Keys](https://repository-service-tuf.readthedocs.io/en/latest/guide/introduction/introduction.html#the-repository-metadata). These Metadata ~~are~~is Root ~~and Targets~~ ([See comment](https://github.com/vmware/repository-service-tuf/issues/208#issuecomment-1386832904)). The current 'bin' role will be removed by #28 
- When the work receives the bootstrap payload, it will create the Snapshot, Timestamp, and the delegated hash bin roles (``bins-{hex}``) using the online keys. It also requires issue #207 to be completed.

### Services it relates to

repository-service-for-tuf-cli, repository-service-for-tuf-api, repository-service-for-tuf-worker

### Related tasks

- #28 
- #207 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
It will require some issues to be implemented in different components.

### Worker

It needs to be modified to take only the `root.json` and the `targets.json`, save it and create and save the hashed BINS delegated roles metadata, the Snapshot Metadata, and the Timestamp Metadata.

The Metadata initialization process for the hashed BINS delegated roles, Snapshot and Timestamp, can be seen in the current CLI Ceremony and implemented in the Worker `repository.MetadataRepository.bootstrap`.

This doesn't break the compatibility with the current CLI once this data is still valid content from the current process.

### CLI

The changes are required in the `cli.admin.ceremony`.

- Remove Snapshot, Timestamp, and BINS keys process loading 
- Remove Target succinct delegation BINS, Snapshot, and Timestamp Metadata creation

### API

Simplify the API Payload contract -- design.
- Remove Snapshot, Timestamp, and BINS from the API payload expected body.

**Comment by MVrachev** [comment]
The three issues for this issue are:
- https://github.com/vmware/repository-service-tuf-cli/issues/177
- https://github.com/vmware/repository-service-tuf-worker/issues/168
- https://github.com/vmware/repository-service-tuf-api/issues/228

**Comment by kairoaraujo** [comment]
To clarify this point in the Issue Description:

> * Create only the Metadata required on the CLI using the [Offline Keys](https://repository-service-tuf.readthedocs.io/en/latest/guide/introduction/introduction.html#the-repository-metadata). These Metadata ~are~is Root ~and Targets~. The current 'bin' role will be removed by [Feature: remove the BIN Keys from Ceremony/Bootstrap Process #28](https://github.com/vmware/repository-service-tuf/issues/28)

On PyPI PEP 458, @lukpueh made an [RFC: PEP 458 Simplifications](https://docs.google.com/document/d/1Z5zZnVy5D4nb_4wQc-lI417CjINr6-ykseqNTFgzUyc) and the proposal is that Targets will also use an online key to use a single online key for all non-root roles.

In that way, we can simplify the RSTUF Bootstrap Ceremony.
I will update the related issues/tasks about this RFC.
Thank you, @lukpueh, for this contribution.

**Comment by kairoaraujo** [comment]
I'm closing this Feature issue as all required tasks are completed.
The remaining task is not a must to have. I'm changing this task to a regular issue.
- https://github.com/vmware/repository-service-tuf-worker/issues/202)
