### ISSUE TITLE
Task: Remove the `BIN` role from the diagrams

### ISSUE THREAD

**Issue by MVrachev** [vmware/repository-service-tuf#212]
### What is the task about?

After all other issues from the components are closed:
- https://github.com/vmware/repository-service-tuf-api/issues/224
- https://github.com/vmware/repository-service-tuf-worker/issues/165
- https://github.com/vmware/repository-service-tuf-cli/issues/174

then we can remove the `BIN` role from the diagrams as well.

### Parent feature

- https://github.com/vmware/repository-service-tuf/issues/28

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
I tried removing all instances of the `bin` word from the repository.
It seems that the only place where we are using it is inside `docs/diagrams/1_1_rstuf_metadata.puml` file.
There I remove the delegation of `targets` to `bin` and remove all places where `bin` delegates to any of the other bins.

Still, after I run `make docs` successfully I see that I have not removed `bin` from this diagram:
<img width="383" alt="image" src="https://user-images.githubusercontent.com/16246778/212491740-75c5af41-2122-4a2f-97d4-52f0d730f85c.png">

I guess it's because, at the moment of writing this, the other components haven't yet removed `bin` in their `main` branches.
Is this diagram from another component?

**Comment by MVrachev** [comment]
After we update the submodules I can try and retry building the diagrams.
@kairoaraujo did you find another way of building the diagrams or should I try the same way as we did up to now?

**Comment by kairoaraujo** [comment]
@MVrachev We can do it in the same way.
Let's fix the FT (https://github.com/vmware/repository-service-tuf-api/pull/239), and we are good to go here.

**Comment by kairoaraujo** [comment]
- Closed by #232
