### ISSUE TITLE
Bug: Functional Tests are failing

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf#222]
### What happened?

Functional Tests are failing

https://github.com/vmware/repository-service-tuf/actions/runs/4004879734/jobs/6874569753

The FT passes local, but is getting HTTP 403 when the ngclient tries to access the metadata https://localhost:8080

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
I identified the issue's root cause.

PR https://github.com/vmware/repository-service-tuf-worker/pull/159 introduced the failure.
Once we, by default, write files in the storage using Unix chmod `0o600` (permission), which makes the files read-only. 

https://github.com/vmware/repository-service-tuf-worker/blob/main/repository_service_tuf_worker/services/storage/local.py#L84-L96

What happens is that Worker's container writes the file to the volume with permission `0o600.`
The HTTP container (running Apache) exposes the files using the `www` user. For Apache security, the files are not accessible, including readable by others, and the HTTP Clients get 403 which is forbidden.

The issue is unreproducible in the development environment because we use python as HTTP Server, which uses the same user and exposes it directly.

We don't need to consider the permission mode `0o600` for the metadata files. It is a security requirement for private keys. The `LocalStorage` writes metadata files that are public and readable to others.

We have two solutions
- Move the `restrict` default to False
- Remove the `restrict` and write the files

**Comment by kairoaraujo** [comment]
I opened the issue in the component 
- https://github.com/vmware/repository-service-tuf-worker/issues/183

We can close this issue when the FT are OK.

**Comment by MVrachev** [comment]
Great job on identifying the root cause!

**Comment by MVrachev** [comment]
Issue https://github.com/vmware/repository-service-tuf-worker/issues/183 was closed and we can update the submodules and run the functional tests again.
If everything is working we can close this issue.

**Comment by kairoaraujo** [comment]
Found another issue
- https://github.com/vmware/repository-service-tuf/actions/runs/4013310896/jobs/6898595197

The fix is proposed here
- https://github.com/vmware/repository-service-tuf-api/pull/239

**Comment by kairoaraujo** [comment]
https://github.com/vmware/repository-service-tuf/actions/runs/4022636805/jobs/6917959303 are passing!
Thank you, @MVrachev!
