### ISSUE TITLE
Task: Document how to import existent targets to RSTUF

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf#226]
### What is the task about?

This task consists in creating documentation in the RSTUF Guide, section Deployment, and how to import the existing Targets to RSTUF.
Important to add to the documentation:
- Required infrastructure and suggestions (large Workers for the data import)
- Some examples with benchmark (i.e.: as used in #188 )
- Steps to import the Data

### Parent feature

- #188

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
We would need to add documentation in the:
- [ ] RSTUF CLI
- [ ] RSTUF umbrella repository: in the deployment section

**Comment by MVrachev** [comment]
We can close this issue after #254 as we have added documentation about this feature in the CLI in prs: https://github.com/vmware/repository-service-tuf-cli/pull/195 and #206.
