### ISSUE TITLE
Bug: the automatic "chore: sync git submodules and docs" is not opened

### ISSUE THREAD

**Issue by MVrachev** [vmware/repository-service-tuf#245]
### What happened?

I noticed that even though we have updated RSTUF CLI 4 days ago we don't receive a new pr "chore: sync git submodules and docs" which updated the documentation and GitHub submodules.

I expect that if there is an update in one of the modules there will be a "chore: sync git submodules and docs" pr in one day after the new commits are merged.

When you open the `RSTUF CLI` reference from this repository you can see it's lagging behind with one commit.

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
This issue can be closed when fixed the below issue
- https://github.com/vmware/repository-service-tuf/issues/245

**Comment by MVrachev** [comment]
I am working on a solution.
I should be able to propose a pr today.
