### ISSUE TITLE
Bug: CI fails

### ISSUE THREAD

**Issue by MVrachev** [vmware/repository-service-tuf#246]
### What happened?

After my last merge #234 the CI is failing:
https://github.com/vmware/repository-service-tuf/actions/runs/4222908551/jobs/7331990999.
I tried to figure out the reason but I see strange behavior.
On one hand, it seems to install the latest version of RSTUF CLI as it fails in a new module called `import_targets.py`, but on another hand fails because it could not find `sqlalchmey` which was added in the RSTUF CLI `requirements-dev.txt` in the same pr as the `import_targets.py` module.

I think this could be connected with issue #245 with that we miss the latest version of the CLI.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
This bug is connected with #245, as @MVrachev mentioned.
It requires a fix in RSTUF CLI. I'm opening an issue in the component and linking to this one.

**Comment by kairoaraujo** [comment]
I'm closing this issue.
We can continue on the issue 
- https://github.com/vmware/repository-service-tuf/issues/245
