### ISSUE TITLE
Feature: remove the BIN Keys from Ceremony/Bootstrap Process

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf#28]
An idea from Jussi talk.

As the CLI Ceremony mentions, 

> Recommended: 2 Keys and Threshold equal 2. Keys discarded after the ceremony.

 - https://github.com/kaprien/kaprien-cli/blob/bee2254d4b67e8c93cb11db18d9da6f0e8ec9ab4/kaprien/cli/admin/ceremony.py#L99
 
1. Remove from the CLI Admin Ceremony step to load targets keys
2. Implement during Ceremony CLI process to generate the targets and discard

**Comment by MVrachev** [comment]
If we decide to remove the BIN keys and instead directly use succinct hash bin delegations in `1.targets.json` this means we will no longer need `1.bin.json`.

**Comment by kairoaraujo** [comment]
I'm sharing my suggestions for this implementation at a high level for you.
It will require some issues to be implemented in different components.

### Worker
_No changes required_

The current `repository.MetadataRepository.bootstrap` is straightforward and saves the roles metadata that is in `payload` sent by the API to the message queue.

This doesn't break the compatibility with the current CLI once this data is still valid content from the current process.
The automatic jobs also don't operate on BIN, as it is an offline key.

### CLI

The CLI is about simplifying `cli.admin.ceremony`, reducing the process.
- Remove the BIN configuration
- Remove the BIN keys loading


### API

The API changes are related to removing BIN from the `bootstrap`

**Comment by MVrachev** [comment]
Isn't more correct to say that we will directly remove the whole `BIN` role?
Then the removal of the `BIN` keys from the ceremony/bootstrap process is a consequence.

**Comment by kairoaraujo** [comment]
> Isn't more correct to say that we will directly remove the whole `BIN` role?
> 
> Then the removal of the `BIN` keys from the ceremony/bootstrap process is a consequence. 

I'm detailing all changes in a way we can break down into small changes/issues. 
So we can file them and understand each change.

**Comment by MVrachev** [comment]
All of the issues that need to be closed in order to close this issue are:
- https://github.com/vmware/repository-service-tuf-api/issues/224
- https://github.com/vmware/repository-service-tuf-worker/issues/165
- https://github.com/vmware/repository-service-tuf-cli/issues/174
- https://github.com/vmware/repository-service-tuf/issues/212

**Comment by kairoaraujo** [comment]
@MVrachev looks like all tasks are done! 🎉 
Well done! Please, have the honor and close this feature issue 🍾

**Comment by MVrachev** [comment]
Hahaha, thanks @kairoaraujo.
Closing 🎉
