### ISSUE TITLE
[Functional tests] Remove targets

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf#48]
Use the Targets API to add new targets.

- Using a valid Token with scope `delete:targets` (maybe a fixture for it),
- Delete at least 5 targets (combine with #47 ?)
- Check the task status
- Measure the time from sending the request, and the targets are removed

Nice to have:
- Use the `python-tuf`, ngclient`, to see when the targets are added in item 4 above.

**Comment by MVrachev** [comment]
I want to take this one.

**Comment by MVrachev** [comment]
Feature file together with functional tests was implemented in https://github.com/vmware/repository-service-tuf/pull/183.
Closing.
