### ISSUE TITLE
Implement dependabot in all repositories

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf#57]
We should plan issues for the repositories to implement dependabot.
- `requirements*.txt`
- GitHub Actions

**Comment by kairoaraujo** [comment]
@rdimitrov, I guess this one can be closed, right?

**Comment by rdimitrov** [comment]
How about we close this one with the one about the updating the Python dependencies automatically?

**Comment by rdimitrov** [comment]
I have a draft PR on that but I have to test it 👍
