### ISSUE TITLE
Other: Feature and Enhancement template doesn't render

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf#89]
### What do you want to share with us?

 Feature and Enhancement template don't render

https://github.com/vmware/repository-service-tuf/blob/main/.github/ISSUE_TEMPLATE/feature.yml
https://github.com/vmware/repository-service-tuf/blob/main/.github/ISSUE_TEMPLATE/enhancement.yml

Those templates were introduced by #

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
Related to #85 
  - #85

**Comment by kairoaraujo** [comment]
I think would be good also add an additional label in the `bug.yml`: needs-triage

**Comment by rdimitrov** [comment]
Thanks, I'll add that too 👍 Once we agree, I'll add the templates that are needed to the rest of the repos too 👍
